### PR TITLE
Add npm and best-torrent plugins to docs

### PR DESCRIPTION
**Pull request by Kamahl19**
The 1st one is for searching packages in npm and the 2nd one is for finding the best possible torrent.

### CODE REVIEW

**Comment by appetizermonster** [comment]
@Kamahl19 Thanks!, I tried your torrent plugin, it works well and looks nice!

**Comment by Kamahl19** [comment]
@appetizermonster Thanks, I am glad you like it. Actually it was not working yesterday, I had a typo I did not noticed in 1.0.3 :( I also borrowed some code from your internal hpm package for my Npm search package. I hope you dont mind :)

**Comment by Kamahl19** [comment]
@appetizermonster Any idea why hain-plugin-npm (https://www.npmjs.com/search?q=hain-plugin-npm) is not searchable in hain? Also this does not work https://npmsearch.com/?q=hain-plugin-npm

**Comment by appetizermonster** [comment]
@Kamahl19 It's okay, it's open source. and I don't know why your plugin isn't appeared on npmsearch.com, I just suppose it would be working if you increment the version and publish again

**Comment by Kamahl19** [comment]
@appetizermonster I bumped the version but it does not work. I suppose npmsearch.com has a bug. I created an Issue https://github.com/solids/npmsearch/issues/32 . Until then I guess hain-plugin-npm wont be installable, right? Maybe I could change the package name? ..

**Pull request merged**
