### PR TITLE
Chocolatey installer

### PR DESCRIPTION
**Pull request by FlorianRappl**
Added a Chocolatey installer (as described in https://github.com/chocolatey/choco/wiki/CreatePackages). Also pushed the Chocolatey package (preliminary version).

If desired I can add you as the owner of the package (you need an account on the Chocolatey website though), such that you can also submit releases (e.g., via an installation script / in the CI with AppVeyor).

### CODE REVIEW

**Comment by luisrudge** [comment]
Awesome!

**Comment by appetizermonster** [comment]
Great job :+1:  i have a question for it. how do i update a package for **Chocolatey** if new version has came up?

**Comment by ishu3101** [comment]
I dont see Hain on the [chocolatey](http://chocolatey.org) website.

**Comment by FlorianRappl** [comment]
Hi @ishu3101 - its just the deployment script. Its not the package. The package is on the Chocolatey website, but as given in the README (please see the changeset) its currently a pre-release. In the README you'll also find the URL of the package (https://chocolatey.org/packages/Hain).

@appetizermonster you need to be owner to update the package. That's why I asked if you want also to become owner. In this case I need to know your account at the Chocolatey website.

One possibility is then to integrate a deployment to Chocolatey as part of the CI with AppVeyor. Updating the package is then as simple as changing the version in *Hain.nuspec* to `$version` and running

```ps
choco pack Hain.nuspec
choco push Hain.$version.nupkg
```

**Comment by ishu3101** [comment]
It's strange that when you search for Hain it does not find the package

**Comment by appetizermonster** [comment]
@FlorianRappl Could you add me as an owner to Chocolatey package? my account on chocolatey is `appetizermonster`

**Comment by FlorianRappl** [comment]
Yep, you are registered now as a maintainer (may take a while until its approved). I've also adjusted the Chocolatey package configuration (specifically, the `owners` field value). If you'd like I can submit another PR reflecting the changes.

The logo should be provided as a PNG - maybe that should still be changed.

**Pull request merged**
