### PR TITLE
Add DEV_PLUGIN_REPO to the plugin context

### PR DESCRIPTION
**Pull request by Metrakit**
This feature is usefull for dev in local

### CODE REVIEW

**Comment by Semigradsky** [comment]
Could you give an example?

**Comment by Metrakit** [comment]
yep, 

```
const jsonfile= `${repo}/hain-plugin-example/jsonfile.json`;
```

**Comment by Semigradsky** [comment]
You can require your JSON just as you would require a js file.
```js
const jsonfile = require('./jsonfile.json');
```

**Comment by Metrakit** [comment]
yep, but not after the plugin is loaded. By example with, the library "node-jsonfile", we cant read or write in the plugin directory without precise the full path.  You can have a try.
Check by friends plugin if you want : https://github.com/k-meissonnier/hain-plugin-snippet/blob/master/index.js. He using '../../' for go to his json file so it's not convenient

**Comment by Metrakit** [comment]
So why have added the LOCAL_PLUGIN_REPO and INTERNAL_PLUGIN_REPO to the plugincontext ? The DEV_PLUGIN_REPO is in the same logic.

**Comment by appetizermonster** [comment]
@Metrakit Nice work!, I think it's useful.

**Pull request merged**
