### PR TITLE
Add button API

### PR DESCRIPTION
**Pull request by Metrakit**
Hi, I'm back, sorry for the late.

I have finally make the button API. 

So here's some examples for use this API in our plugins : 

```javascript
res.add({
    id: id,
    payload: 'open',
    button: {
        className: 'fa fa-clipboard',
        color: '#5fba7d',
        tooltip: 'Copy to clipboard'
    }
});

function buttonAction(id, payload) {
    ncp.copy(id, function() {
        context.toast.enqueue('Pasted to clipboard !');
    });
}

return { startup, search, execute, renderPreview, buttonAction };
```

```javascript
res.add({
    id: id,
    payload: 'open',
    button: {
        className: 'fa fa-external-link',
        color: 'red',
        hoverColor: 'blue',
        tooltip: 'Go to URL'
    }
});

function buttonAction(id, payload) {
    shell.openExternal(id);
}

return { startup, search, execute, renderPreview, buttonAction };
```

Voilà.

All the options for the button API are optionals, you can check it in the code ;)

The options possible are : 

```javascript
button: {
    className: 'fa fa-icon',
    color: '#color',
    hoverColor: '#color',
    tooltip: 'A tooltip'
}
```

If you think it's good and if you want merge it so I can help you to complete the documentation about this new feature :) . 

Hope you will enjoy.

### CODE REVIEW

**Comment by Metrakit** [comment]
Some gifs for a demo hehe : 

gif_hain_button_1

hain_screen_2

**Comment by notatestuser** [comment]
Gifs inside gifs – gif inception!

**Comment by Metrakit** [comment]
@notatestuser haha yeah. Gifs everywhere !

**Comment by appetizermonster** [comment]
Nice PR! :+1:  I'll review it and maybe this will be merged soon.

**Comment by Metrakit** [comment]
@appetizermonster ok, great.

**Comment by cpriest** [comment]
Very nice; didn't realize this was a feature.  Need to add this to the documentation.

**Pull request merged**
