### PR TITLE
Add hain-plugin-material-colors to plugin-docs

### PR DESCRIPTION
**Pull request by aouerfelli**

### CODE REVIEW

**Comment by appetizermonster** [comment]
Please pr to develop branch! :wink:

**Comment by aouerfelli** [comment]
Got it, sorry. Maybe clarifying in share-your-plugins would be beneficial?

**Comment by appetizermonster** [comment]
`share-your-plugins` doesn't have a responsibility for this kind of PR, actually it's related with [CONTRIBUTING.md](https://github.com/appetizermonster/hain/blob/master/CONTRIBUTING.md).

**Comment by aouerfelli** [comment]
Makes sense, I understand.

**Pull request closed without merging**
