### PR TITLE
Window Shortcut Tweaks

### PR DESCRIPTION
**Pull request by cpriest**
Primarily a triggered global shortcut while the hain window is already open will no longer close it.

### CODE REVIEW

**Comment by appetizermonster** [comment]
@cpriest, it seems that your formatting rules isn't same with the old one. especially, the vertical alignment generates unnecessary changes to commit.
in my opinion, it's better to follow the old one. or we can make the new one.
how do you think?

**Comment by appetizermonster** [comment]
for now, i reverted the formatting to follow eslint config, editorconfig at 3b44ee56cc0a7dae7fe521c02fec52e8215d832e, but i'm not saying this is the best.

**Comment by cpriest** [comment]
No problem, I had not setup eslint checking in my IDE before I had sent that in.  I have it setup now (though some of the other files have eslint violations.  I modified the eslint a bit to allow for the violations, they would be "no-restricted-syntax": "off", "no-multi-spaces": "off," that fine?

**Comment by appetizermonster** [comment]
@cpriest That is fine :+1: 
One thing to note is that `package.json` should not be formatted manually. (`npm` will do it)

**Comment by appetizermonster** [comment]
and i have a question, why do you remove toggle function for the shortcut?
I thought it's useful. so i think it's better to make an option to disable it.

**Comment by cpriest** [comment]
Well if I'm pressing a global shortcut key, shouldn't it always show the window?  The way it was, if I had the hain window already opened and pressed a shortcut key, it would close the hain window.  Seemed like a bug to me.

The toggle() function is still there, its just that a global shortcut key will always call show() with the query associated with the shortcut key.

**Comment by appetizermonster** [comment]
then, I'll make an option to switch between `toggle` and `show`, because i prefer `toggle` than `show`, it can hide the window more faster than pressing `esc`

**Comment by cpriest** [comment]
Strange, I didn't see your followup comment @appetizermonster, I can add the toggle as well if you can't get to it right away.

I'm working on a solution to indexing control panel items, UWP apps, etc.  What a PITA.

**Pull request merged**
