### PR TITLE
Rewrite math plugin.

### PR DESCRIPTION
**Pull request by leonardosnt**
demo

### CODE REVIEW

**Comment by appetizermonster** [comment]
thanks for the pull request, i'll try and merge it.

**Comment by appetizermonster** [comment]
@leonardosnt i think it will be nice if there is a prefix like `=` (e.g. `=1+1`, `=1*5+5`)
At this time, it shows a result even if they don't need to.

**Comment by leonardosnt** [comment]
@appetizermonster like this https://github.com/appetizermonster/hain/pull/17/commits/78766eb24e4547ab546ac80baafc3a1c21e086b2?

**Comment by appetizermonster** [comment]
good job!

**Pull request merged**
