### PR TITLE
Add clipboard feature

### PR DESCRIPTION
**Pull request by Metrakit**
Hi !

I have added the clipboard feature in hain , I think it can be really a good idea to use the clipboard API in Hain for enhance our plugins :smile: . I hope you will appreciate my PR, I have added 2 ways to use the clipboard in our plugins and 2 types of data (image and text).

The first possibility is to use in our result object like this : 

```
res.add({
  ...
  clipboard: {
    type: 'text', // or 'image',
    content: 'Text to paste in the clipboard' // or URL or local path for the images
  }
  ...
});
```
With this possibility, an icon with appear on the right to the item list (e.g. on my screens).

And the second is to use the clipboard context : 

```
const clipboard = context.clipboard;
clipboard.set('My text to put in the clipboard');
clipboard.get();
clipboard.setImage('URL or local path');
clipboard.getImage();
clipboard.has();
clipboard.clear();
```
An example in my GIF plugin : 

Example in the code : 
example_code

Icon at right : 
example

With the click event (toast) : 
example_pasted

Voilà, hope you will appreciate it. This will be very useful for our plugins and this PR is related too to this issue : #44 .

++,
Metrakit.

### CODE REVIEW

**Comment by appetizermonster** [comment]
Great!!!!! 
however, I think it will be better to remove buttons for now.
It's better to provide clipboard API & button API separately.

**Comment by appetizermonster** [comment]
@Metrakit 
i think new API would break API compatibility.
(because plugin using new API can show up in the old version Hain)
i have no good idea for how to resolve API compatibility issue.
how do you think?

**Comment by notatestuser** [comment]
How about something like:
```js
module.exports = (pluginContext) => {
  const app = pluginContext.app;
  app.requireVersion(">0.0.3")  // semver; show a "please upgrade" message if this is not satisfied
  const clipboard = pluginContext.clipboard;
  // ...
```

**Comment by Metrakit** [comment]
@appetizermonster, yeah i havent think about the API version but I think the hack from @notatestuser can be good idea for now.

**Comment by Metrakit** [comment]
@appetizermonster ok I remove the button for this API, maybe I will do an API or the button soon

**Comment by Metrakit** [comment]
@appetizermonster Voila, I have remove the button for this feature

**Comment by appetizermonster** [comment]
@Metrakit good!, i'll test it and merge it

**Comment by Metrakit** [comment]
@appetizermonster I think for the next releases, a feature like this can be interesting in the package.json file : 

```
...
"hain": {
    "hain_version": ">0.0.3",
    "prefix": "/trello",
    "usage": "/trello a card",
    "redirect": "/trello ",
    "icon": "/icon.png"
  }
...
```

I think it the best way for can implements new features in the future.

**Comment by Metrakit** [comment]
@appetizermonster ok, thanks !

**Comment by Metrakit** [comment]
@appetizermonster , You think an API button for this use case can be the best way :
```
const clipbloard = context.clipboard;
res.add({
  ...
  button: {
    icon: 'fa fa-clipboard',
    color: '#555555',
    hoverColor: '#888888',
    onClick: clipboard.set('My text to copy in the clipboard')
  }
  ...
});
```
?

**Comment by notatestuser** [comment]
`clipboard.get()` doesn't seem to work - it always returns `undefined`!

**Comment by Metrakit** [comment]
Its work for me, the methods comes from the cliboard API from Electron : https://github.com/atom/electron/blob/master/docs/api/clipboard.md

**Comment by notatestuser** [comment]
Yeah I see that. Strange.




On Mon, Mar 28, 2016 at 10:34 AM -0700, "Jordane" <notifications@github.com> wrote:












Its work for me, the methods comes from the cliboard API from Electron : https://github.com/atom/electron/blob/master/docs/api/clipboard.md

**Comment by notatestuser** [comment]
I'm using Windows 10. Could that be the issue?

**Comment by appetizermonster** [comment]
@Metrakit @notatestuser Good, I'm working on implementing API version resolver by referencing your idea

**Comment by notatestuser** [comment]
It works if I get the clipboard data via `remote.require('clipboard').readText()` in the renderer thread via rpc.

**Comment by notatestuser** [comment]
This is the test I've been doing:
```js
module.exports = (context) => {
  const logger = context.logger;
  const clipboard = context.clipboard;
  function startup() {
    setInterval(() => {
      const clip = clipboard.get();
      logger.log(`Clipboard text: ${clip}`);
    }, 1000);
  }
}
```
And I open the F12 dev tools to check what's in the console. It's always `undefined` unless I use the rpc method.

**Comment by Metrakit** [comment]
Hi @appetizermonster , Can i work on the button API like i have suggested and make a PR or you are working on ?

**Comment by appetizermonster** [comment]
@Metrakit I'm not working on Button API for now, so you can make it.
and I think there is a some errors on this pull request.
I see `docs/plugin-skeleton.md`, `docs/search-result.md` aren't related with Clipboard API

**Comment by Metrakit** [comment]
@appetizermonster ok, I will make a new cleaner PR with only the clipboard API, without the button.

**Comment by notatestuser** [comment]
I plan to test this again with the x64 build on Windows 10. With any luck my issue is resolved.

**Comment by Metrakit** [comment]
I have closed this PR for make a new one there : https://github.com/appetizermonster/hain/pull/132

**Pull request closed without merging**
