### PR TITLE
Added hain-plugin-clipboard to plugin docs

### PR DESCRIPTION
**Pull request by notatestuser**
Added [hain-plugin-clipboard](https://github.com/notatestuser/hain-plugin-clipboard) (plugin-docs.md)

### CODE REVIEW

**Comment by appetizermonster** [comment]
@notatestuser Very nice plugin, i use it everyday haha

**Comment by notatestuser** [comment]
Thanks – I hope to make it work with Korean characters soon!

**Comment by appetizermonster** [comment]
@notatestuser ... it already works well with Korean characters for me :+1:

**Comment by notatestuser** [comment]
Ah. Which version of Windows are you running?

**Comment by appetizermonster** [comment]
Windows 7 and 10

**Comment by notatestuser** [comment]
Hey @appetizermonster could you tell me what you see when you run 'chcp' in a cmd.exe?

**Comment by appetizermonster** [comment]
my active code page is 949 (euc-kr)

**Pull request merged**
