### PR TITLE
Added two of my plugins

### PR DESCRIPTION
**Pull request by KennethWussmann**
`hain-plugin-steam` is an easy to use plugin to start your steam games
`hain-plugin-pc` is an easy to use plugin to shutdown, restart, logout and lock your computer

### CODE REVIEW

**Comment by Braunson** [comment]
@KennethWussmann What versions of Windows does the PC plugin support? It's not specified in your readme. Cheers!

**Comment by KennethWussmann** [comment]
@Braunson I've added this info to my [README.md](https://github.com/KennethWussmann/hain-plugin-steam/blob/master/README.md#supported-windows-versions). (Windows 7-10)

**Comment by appetizermonster** [comment]
@KennethWussmann Thanks for the pull request, i installed your two plugins, and it's awesome, and it has clever implementation

**Comment by appetizermonster** [comment]
oh and, it will be better to send a pull request in the `develop` branch next time

**Comment by KennethWussmann** [comment]
Thanks for your feedback, I read your CONTRIBUTING.md but I thougth pushing to `develop` is just for code and not documentation. I'll note that for my next plugins :wink:

**Pull request merged**
