### PR TITLE
Debian release setup 

### PR DESCRIPTION
**Pull request by ewnd9**
- [x] travis setup

- ~~[ ] `platform-util` files search on Linux~~
- ~~[ ] `platform-util` icon protocol realisation to show file icons in the files search on Linux~~
- ~~[ ] `platform-util` window focus management on Linux~~

~~## travis setup~~
~~- auth on travis with github~~
~~- create oauth token at https://github.com/settings/tokens with `repo` scope~~ 

Demonstration
- ~~`npm install travis-encrypt -g`~~
- ~~`travis-encrypt -r appetizermonster/hain <token>`~~

~~Token (output from `travis-encrypt` should be replaced in  https://github.com/ewnd9/hain/blob/94814828dbdbb65759740de417c0dc289b6da026/.travis.yml#L9~~

~~Right now there is my token for the test repository https://github.com/ewnd9/hain-travis-publish-playground I had to create separate repo in order to test releases (`git tag`) handling~~
~~### Related~~
~~- [travis doc](https://docs.travis-ci.com/user/deployment/releases/)~~

---

debian package for latest version is available at https://github.com/ewnd9/hain-travis-publish-playground/releases/tag/v0.3.33 // cc @toXel (https://github.com/appetizermonster/hain/pull/48#issuecomment-202776087)

related to https://github.com/appetizermonster/hain/issues/98

### CODE REVIEW

**Comment by cpriest** [comment]
@ewnd9  Apologies, I can't fix the merge conflicts from your repo.  I'll merge as soon as you put merge the conflicts though.

**Comment by ewnd9** [comment]
@cpriest Will take a look on the weekend

**Comment by ewnd9** [comment]
@cpriest I've updated the pull request, although now without `travis-ci` setup because it seems it is too cumbersome.

**Comment by cpriest** [comment]
@ewnd9 Thanks for the contribution, I've merged this in.

**Pull request merged**
