### PR TITLE
Add todo plugin

### PR DESCRIPTION
**Pull request by Metrakit**
An easy task manager !

### CODE REVIEW

**Comment by cpriest** [comment]
@appetizermonster are there any procedures/restrictions in place for accepting these changes?

Do you want to review / merge yourself or is reviewing/merging something you'd be okay with me doing now and then?

**Comment by appetizermonster** [comment]
@cpriest Actually, there is no strict rules for merging pull request, I just want to keep code always executable. and don't want to break plugin compatibility. 
I have no enough time for reviewing issues & pull requests these days, so i think you can review and merge pull request if you mind.

**Comment by cpriest** [comment]
@appetizermonster In this case I was referring to any reviewing of the plugin before being allowed to be added to the 'plugins' doc...

**Comment by appetizermonster** [comment]
@cpriest i understand, i always welcome any pull requests for "plugin-docs"

**Comment by cpriest** [comment]
ok

**Comment by cpriest** [comment]
@Metrakit : This has merge conflicts, please resolve those and update the pull request and I'll merge it in.

**Pull request closed without merging**
